In [1]:
!pip install dbrepo

Requirement already satisfied: dbrepo in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (1.13.8)
Requirement already satisfied: requests>=2.31 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from dbrepo) (2.32.5)
Requirement already satisfied: pika in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from dbrepo) (1.4.1)
Requirement already satisfied: pydantic in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from dbrepo) (2.13.4)
Requirement already satisfied: pandas in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from dbrepo) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from requests>=2.31->dbrepo) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from requests>=2.31->dbrepo) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from requests>=2.31->dbrepo) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from requests>=2.31->dbrepo) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pandas->dbrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pandas->dbrepo) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->dbrepo) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pydantic->dbrepo) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pydantic->dbrepo) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pydantic->dbrepo) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/gokayyil/miniforge3/lib/python3.13/site-packages (from pydantic->dbrepo) (0.4.2)

In [4]:
from dbrepo.RestClient import RestClient

client = RestClient(
    endpoint="https://test.dbrepo.tuwien.ac.at",
    username="gokayyil",
    password="123123Go."
)

print(client.whoami())

gokayyil
gokayyil

In [6]:
databases = client.get_databases()

for db in databases:
    print(db)

id='5cde660e-153a-4bff-8e41-69e87cda399d' name='dast_g20_wastewater_epidemiology' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='dast_g20_wastewater_epidemiology_ndfx' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='b3d4fde4-e0f5-441c-977b-d3c93e03e3e8', database_id='5cde660e-153a-4bff-8e41-69e87cda399d', type=<IdentifierType.DATABASE: 'database'>, owned_by='data_stewardship_group20', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2026, publisher='EUDA & SCORE, EUROSTAT, TU Wien', titles=[IdentifierTitle(id='57af7e20-47db-4ba7-a6a1-7ce594fba3e0', title='Predictive Modeling of Regional GDP based on Wastewater-Based Epidemiology', language=<Language.EN: 'en'>, type=None)], doi='10.82556/pbwe-bk06', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='ea768898-e9ee-4db7-83fe-6d533a85ef9e' name='data_stewardship_group6_crash_serverity_prediction_lkhb' contact=UserBrief(username='sebastianschnitzer', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='sebastianschnitzer' internal_name='data_stewardship_group6_crash_serverity_prediction_lkhb_m7hf' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='fa7a64a0-dc27-46ac-81f6-7699122837b7', database_id='ea768898-e9ee-4db7-83fe-6d533a85ef9e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright - Department for Transport, United Kingdom', titles=[IdentifierTitle(id='16ff4a6f-142c-49d7-85bf-0b361792816c', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/mb8m-zn90', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='ed890fa1-154c-4a66-8529-4088c97f68db' name='no2_air_quality_classification_austria' contact=UserBrief(username='sinasadeghi', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='sinasadeghi' internal_name='no2_air_quality_classification_austria_jlnb' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='859c9b81-fcfb-4808-aea6-9d14fa2a8b2e', database_id='ed890fa1-154c-4a66-8529-4088c97f68db', type=<IdentifierType.DATABASE: 'database'>, owned_by='12353396', status=<IdentifierStatusType.PUBLISHED: 'published'>, publication_year=2026, publisher='TU Wien', titles=[IdentifierTitle(id='0a0b70e1-10cd-497f-a90d-d2cfc2001efe', title='NO2 Air Quality Classification across Austrian Monitoring Stations', language=<Language.EN: 'en'>, type=<TitleType.OTHER: 'Other'>)], doi='10.82556/3zan-dn41', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='f8760aae-3d51-48b2-9588-926f9a5f29ab', database_id='ed890fa1-154c-4a66-8529-4088c97f68db', type=<IdentifierType.DATABASE: 'database'>, owned_by='12353396', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2026, publisher='TU Wien', titles=[IdentifierTitle(id='8f55d237-b5ec-433f-8904-a87ddd7312bb', title='NO2 Air Quality Classification across Austrian Monitoring Stations', language=<Language.EN: 'en'>, type=<TitleType.OTHER: 'Other'>)], doi='10.82556/nw1x-t340', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='120b7da3-ee6d-401d-8046-640d7b736d9f' name='test_2_g6' contact=UserBrief(username='12549571', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='12549571' internal_name='test_2_g6_zohx' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='995671b5-2bcc-4c2e-b7cd-773466ee115b' name='test_g6' contact=UserBrief(username='12549571', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='12549571' internal_name='test_g6_bxl9' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='3e330351-7176-41a1-8964-ad9292183d2d', database_id='995671b5-2bcc-4c2e-b7cd-773466ee115b', type=<IdentifierType.DATABASE: 'database'>, owned_by='12549571', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright - Department for Transport, United Kingdom', titles=[IdentifierTitle(id='60d653cc-eae1-434f-a0ec-d85a813b220a', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/gpcx-yx56', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='6cd08fa6-8665-4dda-89b3-075813539d99', database_id='995671b5-2bcc-4c2e-b7cd-773466ee115b', type=<IdentifierType.DATABASE: 'database'>, owned_by='12549571', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright - Department for Transport, United Kingdom', titles=[IdentifierTitle(id='a2be2a04-bb22-47cd-b9a8-550c95829e28', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/xkm7-8q09', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='3a83ad5f-8c71-4ad0-ad2a-3562b553ec1f', database_id='995671b5-2bcc-4c2e-b7cd-773466ee115b', type=<IdentifierType.DATABASE: 'database'>, owned_by='12549571', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright - Department for Transport, United Kingdom', titles=[IdentifierTitle(id='721f570f-13a0-4aea-897b-7a3a4fa595c1', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/bckc-yn64', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='9980c36f-7e9a-4779-8c65-9a6f6054294e' name='dast_g20_wastewater_epidemiology' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='dast_g20_wastewater_epidemiology_pbmz' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='fa06ed94-d16a-4829-8553-bfb745f905d2', database_id='9980c36f-7e9a-4779-8c65-9a6f6054294e', type=<IdentifierType.DATABASE: 'database'>, owned_by='data_stewardship_group20', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2026, publisher='EUDA & SCORE, EUROSTAT', titles=[IdentifierTitle(id='01e01d20-6f88-4527-946b-1f7bf22db9b4', title='Predictive Modeling of Regional GDP based on Wastewater-Based Epidemiology', language=<Language.EN: 'en'>, type=None)], doi='10.82556/1zb9-pv78', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='coffee_productivity_prediction' contact=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='gokayyil' internal_name='coffee_productivity_prediction_wbmm' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='09823bb9-567d-4e03-b78f-d64ff1c323df' name='water_quality_prediction' contact=UserBrief(username='12534788', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='12534788' internal_name='water_quality_prediction_2dfe' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='10dfb46a-bc0b-47bc-9802-e927a33c5e75' name='SDCC Traffic Flow Experiment 2022' contact=UserBrief(username='ahmadhabib', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='ahmadhabib' internal_name='sdcc_traffic_flow_experiment_2022_d2ks' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='60416114-a982-49ca-a614-3791ec478000' name='SDCC Traffic Flow Experiment 2022' contact=UserBrief(username='ahmadhabib', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='ahmadhabib' internal_name='sdcc_traffic_flow_experiment_2022_ttot' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='71717f2f-610f-4930-8451-7600c874b78b' name='SDCC Traffic Flow Experiment 2022' contact=UserBrief(username='ahmadhabib', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='ahmadhabib' internal_name='sdcc_traffic_flow_experiment_2022_3afw' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='598ce585-d8b5-4a97-8f19-cb085d4a5b1e' name='football_player_valuation' contact=UserBrief(username='ekene', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='ekene' internal_name='football_player_valuation_pp6w' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='78d4e05e-262c-49e0-93d3-29d1145c967e', database_id='598ce585-d8b5-4a97-8f19-cb085d4a5b1e', type=<IdentifierType.DATABASE: 'database'>, owned_by='ekene', status=<IdentifierStatusType.PUBLISHED: 'published'>, publication_year=2026, publisher='TU Wien', titles=[IdentifierTitle(id='a158cc27-a227-4479-b3f7-6cddfed5ddbf', title='Predicting the Market Value of Football Players Using Various Factors', language=<Language.EN: 'en'>, type=<TitleType.ALTERNATIVE_TITLE: 'AlternativeTitle'>)], doi='10.82556/csyx-ny65', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='a181cad5-4bdb-48b2-937e-3e75293f6a7b' name='vienna_weather_wet_months' contact=UserBrief(username='azra1558', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='azra1558' internal_name='vienna_weather_wet_months_alk8' is_public=False is_schema_public=True identifiers=[] preview_image=None description=None
id='13457a52-37f9-48d4-a078-6865e8d35981' name='lake_water_quality' contact=UserBrief(username='12534814', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='12534814' internal_name='lake_water_quality_hghq' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='cf27a11d-58e5-4693-856c-e8f3527e3394' name='dast_g20_wastewater_epidemiology' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='dast_g20_wastewater_epidemiology_1kph' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='c8950260-4602-4fa9-adc5-e45a66cc9cfa' name='Leeds Traffic and Cheese Exploration DB' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='leeds_traffic_and_cheese_exploration_db_dfis' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='5ef49dd2-39f3-462e-8ef8-42d23d6d49a7' name='Leeds Traffic and Cheese Exploration DB' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='leeds_traffic_and_cheese_exploration_db_losu' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='3d81c073-e5fd-49b9-9536-b75ed490ca3e' name='Data Stewardship Group6 Crash Serverity Prediction' contact=UserBrief(username='sebastianschnitzer', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='sebastianschnitzer' internal_name='data_stewardship_group6_crash_serverity_prediction_lkhb' is_public=True is_schema_public=True identifiers=[IdentifierBrief(id='4065f645-37be-4b87-9282-64a49c23b8a5', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='a0f3597d-0bd4-42cd-a508-7503c7c48012', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/b2dr-2533', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='4618bf62-0051-41fe-b6b5-80db4762cd11', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='9d18debf-3f41-4a11-9f88-3c0134c15a1c', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/vps1-2m24', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='184c5b74-e92f-44d5-a1e8-7d861e789e59', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright - Department for Transport, United Kingdom', titles=[IdentifierTitle(id='6d2f100d-22a7-4e63-b7e0-addabfd89318', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/0xeb-9693', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='1f349a92-cb05-46a7-9205-275b376098f8', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='1ca434fb-19fe-423b-9bb9-bd258090b316', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/sg5y-wg06', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='4e4f4e92-514a-4504-8e5f-728a03dfdedd', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='9fd9642a-aeb2-4210-9f79-a97a508a9ac8', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/00bx-1a39', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='a386c8b0-96c3-4ed7-af7b-158c8e5d94ed', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='eda084a7-e539-4a54-b541-9ab3ab822a30', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/zk50-tw57', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='eca08677-06ae-4989-a4a0-88221e47f8e6', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='a46014dc-0ec6-4978-b66d-d4d6c3928173', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/r53t-dn29', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='4410a3c2-8d88-480a-b246-59c5174812a5', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='f212f6a3-312e-4ea7-8db9-2aacb49ff802', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/j4tt-fc21', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='3c710496-ca5c-449a-9f85-b3ea7d2d8809', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.DRAFT: 'draft'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='6f4ef256-b9b6-406c-bb2e-2c62568add9a', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/6q4h-s990', query_id=None, table_id=None, view_id=None), IdentifierBrief(id='f19cd016-bdb8-48d2-80c8-53d98469c320', database_id='3d81c073-e5fd-49b9-9536-b75ed490ca3e', type=<IdentifierType.DATABASE: 'database'>, owned_by='sebastianschnitzer', status=<IdentifierStatusType.PUBLISHED: 'published'>, publication_year=2023, publisher='Crown Copyright – Department for Transport, United Kingdom', titles=[IdentifierTitle(id='9ad93ac3-4f2f-4b1b-9cc2-56737eae1185', title='UK Road Safety Open Data 2023', language=<Language.EN: 'en'>, type=<TitleType.SUBTITLE: 'Subtitle'>)], doi='10.82556/9860-tg19', query_id=None, table_id=None, view_id=None)] preview_image=None description=None
id='802f81fd-12d8-4474-a2a6-d0afa1a346c8' name='Test Upload FRESH' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='test_upload_fresh_knet' is_public=False is_schema_public=True identifiers=[] preview_image=None description=None
id='03aeee0c-e035-4c61-8132-56bcd1d01b84' name='Test Upload FRESH' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='test_upload_fresh_mzsx' is_public=False is_schema_public=True identifiers=[] preview_image=None description=None
id='0285fdb3-7d86-4c0b-9761-6a7231eac865' name='Test Upload FRESH' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='test_upload_fresh_hmks' is_public=False is_schema_public=True identifiers=[] preview_image=None description=None
id='f1cde5b0-e37b-4bf6-af07-32163b877cda' name='Predicting Road Traffic Accident Severity' contact=UserBrief(username='data_stewardship_group20', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='data_stewardship_group20' internal_name='predicting_road_traffic_accident_severity_ln8g' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='629a32a9-9451-442d-a145-0a0fc57fa080' name='chris_rta_views_test' contact=UserBrief(username='chrisvenator', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='chrisvenator' internal_name='chris_rta_views_test_gmv4' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None
id='8de1e966-ce8a-4b2f-ab11-3f957ebdd45d' name='SDCC Traffic Flow Experiment 2022' contact=UserBrief(username='e12427543', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) owned_by='e12427543' internal_name='sdcc_traffic_flow_experiment_2022_w8n5' is_public=True is_schema_public=True identifiers=[] preview_image=None description=None

In [7]:
database_id = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

tables = client.get_tables(database_id)

for t in tables:
    print(t)

id='9abc69b3-932e-4a20-93a6-9e3cb4ac9676' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='health_metrics' description='Table containing BMI, heart rate, and reported health issue category.' internal_name='health_metrics' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='dddb6b09-ba3f-4003-bf93-73786410e886' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='lifestyle_metrics' description='Table containing stress level, physical activity duration, smoking status, and alcohol consumption status.' internal_name='lifestyle_metrics' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='6e828acb-4698-4f34-9a62-1a753b768554' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='coffee_consumption' description='Table containing daily coffee intake in cups and daily caffeine intake in milligrams.' internal_name='coffee_consumption' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='83a691e2-a7ad-4b5a-b468-03c3d63d727b' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='sleep_metrics' description='Table containing sleep duration and sleep quality information.' internal_name='sleep_metrics' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='913c5c1d-3e46-4393-9e5e-744ab04e0ad2' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='participants' description='Core participant table containing participant identifier, age, and foreign keys to demographic lookup tables.' internal_name='participants' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='8a73da1b-c5b1-4666-968c-ac1d47dbcbc7' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='occupations' description='Lookup table containing participant occupation categories.' internal_name='occupations' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='e5980c01-dacf-481a-84f8-1f83bd84095c' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='genders' description='Lookup table containing participant gender categories.' internal_name='genders' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'
id='018641cc-175b-4fff-b05c-b5afe4d9733c' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='countries' description='Lookup table containing country names used in the dataset.' internal_name='countries' is_versioned=True is_public=True is_schema_public=True owned_by='gokayyil'

In [8]:
database_id = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

for table in client.get_tables(database_id):
    print("\n====================")
    print(table.name)
    print("====================")

    cols = client.get_columns(table.id)

    for c in cols:
        print(c.name)

====================
health_metrics
====================

AttributeError: 'RestClient' object has no attribute 'get_columns'

In [9]:
for m in dir(client):
    if not m.startswith("_"):
        print(m)

analyse_datatypes
analyse_keys
analyse_table_statistics
create_container
create_database
create_database_access
create_identifier
create_subset
create_table
create_table_data
create_view
delete_container
delete_database_access
delete_table
delete_table_data
delete_view
endpoint
get_concepts
get_container
get_containers
get_database
get_database_access
get_databases
get_databases_count
get_identifier
get_identifier_data
get_identifiers
get_image
get_images
get_licenses
get_messages
get_ontologies
get_queries
get_subset
get_subset_data
get_subset_data_count
get_table
get_table_data
get_table_data_count
get_table_history
get_tables
get_units
get_user
get_users
get_view
get_view_data
get_view_data_count
get_views
import_table_data
password
publish_identifier
secure
update_database_access
update_database_owner
update_database_schema
update_database_visibility
update_identifier
update_subset
update_table_column
update_table_data
update_table_statistics
update_user
update_view
username
whoami

In [10]:
participants_id = "913c5c1d-3e46-4393-9e5e-744ab04e0ad2"

data = client.get_table_data(
    table_id=participants_id,
    limit=5
)

print(data)

TypeError: RestClient.get_table_data() got an unexpected keyword argument 'limit'

In [11]:
help(client.get_table_data)

Help on method get_table_data in module dbrepo.RestClient:

get_table_data(
    database_id: str,
    table_id: str,
    page: int = 0,
    size: int = 1000000,
    timestamp: datetime.datetime = None
) -> pandas.DataFrame method of dbrepo.RestClient.RestClient instance
    Get data of a table in a database with the given database id and table id.

    :param database_id: The database id.
    :param table_id: The table id.
    :param page: The result pagination number. Optional. Default: `0`.
    :param size: The result pagination size. Optional. Default: `1000000`.
    :param timestamp: The query execution time. Optional.

    :returns: The table data, if successful.

    :raises MalformedError: If the payload is rejected by the service.
    :raises ForbiddenError: If something went wrong with the authorization.
    :raises NotExistsError: If the table does not exist.
    :raises ServiceError: If something went wrong with obtaining the information in the metadata service.
    :raises ResponseCodeError: If something went wrong with the retrieval.

In [12]:
database_id = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

for table in client.get_tables(database_id):
    print("\n====================")
    print(table.name)
    print("====================")

    df = client.get_table_data(
        database_id,
        table.id,
        page=0,
        size=5
    )

    print(df.columns.tolist())

====================
health_metrics
====================
['bmi', 'health_issues', 'heart_rate_bpm', 'participant_id']

====================
lifestyle_metrics
====================
['alcohol_consumption', 'participant_id', 'physical_activity_hours', 'smoking', 'stress_level']

====================
coffee_consumption
====================
['caffeine_mg_per_day', 'coffee_intake_cups_per_day', 'participant_id']

====================
sleep_metrics
====================
['participant_id', 'sleep_hours', 'sleep_quality']

====================
participants
====================
['age', 'country_id', 'gender_id', 'occupation_id', 'participant_id']

====================
occupations
====================
['occupation_id', 'occupation_name']

====================
genders
====================
['gender_id', 'gender_name']

====================
countries
====================
['country_id', 'country_name']

In [13]:
import inspect

print(inspect.signature(client.create_view))

(database_id: str, name: str, query: dbrepo.api.dto.QueryDefinition, is_public: bool, is_schema_public: bool) -> dbrepo.api.dto.ViewBrief

In [14]:
print(inspect.signature(client.create_subset))

(database_id: str, query: dbrepo.api.dto.QueryDefinition, page: int = 0, size: int = 1000000, timestamp: datetime.datetime = None) -> pandas.DataFrame

In [15]:
from dbrepo.api.dto import QueryDefinition

help(QueryDefinition)

Help on class QueryDefinition in module dbrepo.api.dto:

class QueryDefinition(pydantic.main.BaseModel)
 |  QueryDefinition(**data: 'Any') -> 'None'
 |
 |  Method resolution order:
 |      QueryDefinition
 |      pydantic.main.BaseModel
 |      builtins.object
 |
 |  Data descriptors defined here:
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'columns': 'List[str]', 'datasources': 'List[str]',...
 |
 |  __class_vars__ = set()
 |
 |  __private_attributes__ = {}
 |
 |  __pydantic_complete__ = True
 |
 |  __pydantic_computed_fields__ = {}
 |
 |  __pydantic_core_schema__ = {'cls': <class 'dbrepo.api.dto.QueryDefinit...
 |
 |  __pydantic_custom_init__ = False
 |
 |  __pydantic_decorators__ = DecoratorInfos(validators={}, field_validato...
 |
 |  __pydantic_extra_info__ = None
 |
 |  __pydantic_fields__ = {'columns': FieldInfo(annotation=List[str], requ...
 |
 |  __pydantic_generic_metadata__ = {'args': (), 'origin': None, 'paramete...
 |
 |  __pydantic_parent_namespace__ = None
 |
 |  __pydantic_post_init__ = None
 |
 |  __pydantic_serializer__ = SchemaSerializer(serializer=PolymorphismTram...
 |
 |  __pydantic_setattr_handlers__ = {}
 |
 |  __pydantic_validator__ = SchemaValidator(title="QueryDefinition", vali...
 |
 |  model_config = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pydantic.main.BaseModel:
 |
 |  __copy__(self) -> 'Self'
 |      Returns a shallow copy of the model.
 |
 |  __deepcopy__(self, memo: 'dict[int, Any] | None' = None) -> 'Self'
 |      Returns a deep copy of the model.
 |
 |  __delattr__(self, item: 'str') -> 'Any'
 |      Implement delattr(self, name).
 |
 |  __eq__(self, other: 'Any') -> 'bool'
 |      Return self==value.
 |
 |  __getattr__(self, item: 'str') -> 'Any'
 |
 |  __getstate__(self) -> 'dict[Any, Any]'
 |      Helper for pickle.
 |
 |  __init__(self, /, **data: 'Any') -> 'None'
 |      Create a new model by parsing and validating input data from keyword arguments.
 |
 |      Raises [`ValidationError`][pydantic_core.ValidationError] if the input data cannot be
 |      validated to form a valid model.
 |
 |      `self` is explicitly positional-only to allow `self` as a field name.
 |
 |  __iter__(self) -> 'TupleGenerator'
 |      So `dict(model)` works.
 |
 |  __pretty__(self, fmt: 'Callable[[Any], Any]', **kwargs: 'Any') -> 'Generator[Any]' from pydantic._internal._repr.Representation
 |      Used by devtools (https://python-devtools.helpmanual.io/) to pretty print objects.
 |
 |  __replace__(self, **changes: 'Any') -> 'Self'
 |      # Because we make use of `@dataclass_transform()`, `__replace__` is already synthesized by
 |      # type checkers, so we define the implementation in this `if not TYPE_CHECKING:` block:
 |
 |  __repr__(self) -> 'str'
 |      Return repr(self).
 |
 |  __repr_args__(self) -> '_repr.ReprArgs'
 |
 |  __repr_name__(self) -> 'str' from pydantic._internal._repr.Representation
 |      Name of the instance's class, used in __repr__.
 |
 |  __repr_recursion__(self, object: 'Any') -> 'str' from pydantic._internal._repr.Representation
 |      Returns the string representation of a recursive object.
 |
 |  __repr_str__(self, join_str: 'str') -> 'str' from pydantic._internal._repr.Representation
 |
 |  __rich_repr__(self) -> 'RichReprResult' from pydantic._internal._repr.Representation
 |      Used by Rich (https://rich.readthedocs.io/en/stable/pretty.html) to pretty print objects.
 |
 |  __setattr__(self, name: 'str', value: 'Any') -> 'None'
 |      Implement setattr(self, name, value).
 |
 |  __setstate__(self, state: 'dict[Any, Any]') -> 'None'
 |
 |  __str__(self) -> 'str'
 |      Return str(self).
 |
 |  copy(
 |      self,
 |      *,
 |      include: 'AbstractSetIntStr | MappingIntStrAny | None' = None,
 |      exclude: 'AbstractSetIntStr | MappingIntStrAny | None' = None,
 |      update: 'Dict[str, Any] | None' = None,
 |      deep: 'bool' = False
 |  ) -> 'Self'
 |      Returns a copy of the model.
 |
 |      !!! warning "Deprecated"
 |          This method is now deprecated; use `model_copy` instead.
 |
 |      If you need `include` or `exclude`, use:
 |
 |      ```python {test="skip" lint="skip"}
 |      data = self.model_dump(include=include, exclude=exclude, round_trip=True)
 |      data = {**data, **(update or {})}
 |      copied = self.model_validate(data)
 |      ```
 |
 |      Args:
 |          include: Optional set or mapping specifying which fields to include in the copied model.
 |          exclude: Optional set or mapping specifying which fields to exclude in the copied model.
 |          update: Optional dictionary of field-value pairs to override field values in the copied model.
 |          deep: If True, the values of fields that are Pydantic models will be deep-copied.
 |
 |      Returns:
 |          A copy of the model with included, excluded and updated fields as specified.
 |
 |  dict(
 |      self,
 |      *,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      by_alias: 'bool' = False,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False
 |  ) -> 'Dict[str, Any]'
 |
 |  json(
 |      self,
 |      *,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      by_alias: 'bool' = False,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      encoder: 'Callable[[Any], Any] | None' = PydanticUndefined,
 |      models_as_dict: 'bool' = PydanticUndefined,
 |      **dumps_kwargs: 'Any'
 |  ) -> 'str'
 |
 |  model_copy(
 |      self,
 |      *,
 |      update: 'Mapping[str, Any] | None' = None,
 |      deep: 'bool' = False
 |  ) -> 'Self'
 |      !!! abstract "Usage Documentation"
 |          [`model_copy`](../concepts/models.md#model-copy)
 |
 |      Returns a copy of the model.
 |
 |      !!! note
 |          The underlying instance's [`__dict__`][object.__dict__] attribute is copied. This
 |          might have unexpected side effects if you store anything in it, on top of the model
 |          fields (e.g. the value of [cached properties][functools.cached_property]).
 |
 |      Args:
 |          update: Values to change/add in the new model. Note: the data is not validated
 |              before creating the new model. You should trust this data.
 |          deep: Set to `True` to make a deep copy of the model.
 |
 |      Returns:
 |          New model instance.
 |
 |  model_dump(
 |      self,
 |      *,
 |      mode: "Literal['json', 'python'] | str" = 'python',
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      context: 'Any | None' = None,
 |      by_alias: 'bool | None' = None,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      exclude_computed_fields: 'bool' = False,
 |      round_trip: 'bool' = False,
 |      warnings: "bool | Literal['none', 'warn', 'error']" = True,
 |      fallback: 'Callable[[Any], Any] | None' = None,
 |      serialize_as_any: 'bool' = False,
 |      polymorphic_serialization: 'bool | None' = None
 |  ) -> 'dict[str, Any]'
 |      !!! abstract "Usage Documentation"
 |          [`model_dump`](../concepts/serialization.md#python-mode)
 |
 |      Generate a dictionary representation of the model, optionally specifying which fields to include or exclude.
 |
 |      Args:
 |          mode: The mode in which `to_python` should run.
 |              If mode is 'json', the output will only contain JSON serializable types.
 |              If mode is 'python', the output may contain non-JSON-serializable Python objects.
 |          include: A set of fields to include in the output.
 |          exclude: A set of fields to exclude from the output.
 |          context: Additional context to pass to the serializer.
 |          by_alias: Whether to use the field's alias in the dictionary key if defined.
 |          exclude_unset: Whether to exclude fields that have not been explicitly set.
 |          exclude_defaults: Whether to exclude fields that are set to their default value.
 |          exclude_none: Whether to exclude fields that have a value of `None`.
 |          exclude_computed_fields: Whether to exclude computed fields.
 |              While this can be useful for round-tripping, it is usually recommended to use the dedicated
 |              `round_trip` parameter instead.
 |          round_trip: If True, dumped values should be valid as input for non-idempotent types such as Json[T].
 |          warnings: How to handle serialization errors. False/"none" ignores them, True/"warn" logs errors,
 |              "error" raises a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError].
 |          fallback: A function to call when an unknown value is encountered. If not provided,
 |              a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError] error is raised.
 |          serialize_as_any: Whether to serialize fields with duck-typing serialization behavior.
 |          polymorphic_serialization: Whether to use model and dataclass polymorphic serialization for this call.
 |
 |      Returns:
 |          A dictionary representation of the model.
 |
 |  model_dump_json(
 |      self,
 |      *,
 |      indent: 'int | None' = None,
 |      ensure_ascii: 'bool' = False,
 |      include: 'IncEx | None' = None,
 |      exclude: 'IncEx | None' = None,
 |      context: 'Any | None' = None,
 |      by_alias: 'bool | None' = None,
 |      exclude_unset: 'bool' = False,
 |      exclude_defaults: 'bool' = False,
 |      exclude_none: 'bool' = False,
 |      exclude_computed_fields: 'bool' = False,
 |      round_trip: 'bool' = False,
 |      warnings: "bool | Literal['none', 'warn', 'error']" = True,
 |      fallback: 'Callable[[Any], Any] | None' = None,
 |      serialize_as_any: 'bool' = False,
 |      polymorphic_serialization: 'bool | None' = None
 |  ) -> 'str'
 |      !!! abstract "Usage Documentation"
 |          [`model_dump_json`](../concepts/serialization.md#json-mode)
 |
 |      Generates a JSON representation of the model using Pydantic's `to_json` method.
 |
 |      Args:
 |          indent: Indentation to use in the JSON output. If None is passed, the output will be compact.
 |          ensure_ascii: If `True`, the output is guaranteed to have all incoming non-ASCII characters escaped.
 |              If `False` (the default), these characters will be output as-is.
 |          include: Field(s) to include in the JSON output.
 |          exclude: Field(s) to exclude from the JSON output.
 |          context: Additional context to pass to the serializer.
 |          by_alias: Whether to serialize using field aliases.
 |          exclude_unset: Whether to exclude fields that have not been explicitly set.
 |          exclude_defaults: Whether to exclude fields that are set to their default value.
 |          exclude_none: Whether to exclude fields that have a value of `None`.
 |          exclude_computed_fields: Whether to exclude computed fields.
 |              While this can be useful for round-tripping, it is usually recommended to use the dedicated
 |              `round_trip` parameter instead.
 |          round_trip: If True, dumped values should be valid as input for non-idempotent types such as Json[T].
 |          warnings: How to handle serialization errors. False/"none" ignores them, True/"warn" logs errors,
 |              "error" raises a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError].
 |          fallback: A function to call when an unknown value is encountered. If not provided,
 |              a [`PydanticSerializationError`][pydantic_core.PydanticSerializationError] error is raised.
 |          serialize_as_any: Whether to serialize fields with duck-typing serialization behavior.
 |          polymorphic_serialization: Whether to use model and dataclass polymorphic serialization for this call.
 |
 |      Returns:
 |          A JSON string representation of the model.
 |
 |  model_post_init(self, context: 'Any', /) -> 'None'
 |      Override this method to perform additional initialization after `__init__` and `model_construct`.
 |      This is useful if you want to do some validation that requires the entire model to be initialized.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from pydantic.main.BaseModel:
 |
 |  __class_getitem__(typevar_values: 'type[Any] | tuple[type[Any], ...]') -> 'type[BaseModel] | _forward_ref.PydanticRecursiveRef'
 |
 |  __get_pydantic_core_schema__(
 |      source: 'type[BaseModel]',
 |      handler: 'GetCoreSchemaHandler',
 |      /
 |  ) -> 'CoreSchema'
 |
 |  __get_pydantic_json_schema__(
 |      core_schema: 'CoreSchema',
 |      handler: 'GetJsonSchemaHandler',
 |      /
 |  ) -> 'JsonSchemaValue'
 |      Hook into generating the model's JSON schema.
 |
 |      Args:
 |          core_schema: A `pydantic-core` CoreSchema.
 |              You can ignore this argument and call the handler with a new CoreSchema,
 |              wrap this CoreSchema (`{'type': 'nullable', 'schema': current_schema}`),
 |              or just call the handler with the original schema.
 |          handler: Call into Pydantic's internal JSON schema generation.
 |              This will raise a `pydantic.errors.PydanticInvalidForJsonSchema` if JSON schema
 |              generation fails.
 |              Since this gets called by `BaseModel.model_json_schema` you can override the
 |              `schema_generator` argument to that function to change JSON schema generation globally
 |              for a type.
 |
 |      Returns:
 |          A JSON schema, as a Python object.
 |
 |  __pydantic_init_subclass__(**kwargs: 'Any') -> 'None'
 |      This is intended to behave just like `__init_subclass__`, but is called by `ModelMetaclass`
 |      only after basic class initialization is complete. In particular, attributes like `model_fields` will
 |      be present when this is called, but forward annotations are not guaranteed to be resolved yet,
 |      meaning that creating an instance of the class may fail.
 |
 |      This is necessary because `__init_subclass__` will always be called by `type.__new__`,
 |      and it would require a prohibitively large refactor to the `ModelMetaclass` to ensure that
 |      `type.__new__` was called in such a manner that the class would already be sufficiently initialized.
 |
 |      This will receive the same `kwargs` that would be passed to the standard `__init_subclass__`, namely,
 |      any kwargs passed to the class definition that aren't used internally by Pydantic.
 |
 |      Args:
 |          **kwargs: Any keyword arguments passed to the class definition that aren't used internally
 |              by Pydantic.
 |
 |      Note:
 |          You may want to override [`__pydantic_on_complete__()`][pydantic.main.BaseModel.__pydantic_on_complete__]
 |          instead, which is called once the class and its fields are fully initialized and ready for validation.
 |
 |  __pydantic_on_complete__() -> 'None'
 |      This is called once the class and its fields are fully initialized and ready to be used.
 |
 |      This typically happens when the class is created (just before
 |      [`__pydantic_init_subclass__()`][pydantic.main.BaseModel.__pydantic_init_subclass__] is called on the superclass),
 |      except when forward annotations are used that could not immediately be resolved.
 |      In that case, it will be called later, when the model is rebuilt automatically or explicitly using
 |      [`model_rebuild()`][pydantic.main.BaseModel.model_rebuild].
 |
 |  construct(_fields_set: 'set[str] | None' = None, **values: 'Any') -> 'Self'
 |
 |  from_orm(obj: 'Any') -> 'Self'
 |
 |  model_construct(_fields_set: 'set[str] | None' = None, **values: 'Any') -> 'Self'
 |      Creates a new instance of the `Model` class with validated data.
 |
 |      Creates a new model setting `__dict__` and `__pydantic_fields_set__` from trusted or pre-validated data.
 |      Default values are respected, but no other validation is performed.
 |
 |      !!! note
 |          `model_construct()` generally respects the `model_config.extra` setting on the provided model.
 |          That is, if `model_config.extra == 'allow'`, then all extra passed values are added to the model instance's `__dict__`
 |          and `__pydantic_extra__` fields. If `model_config.extra == 'ignore'` (the default), then all extra passed values are ignored.
 |          Because no validation is performed with a call to `model_construct()`, having `model_config.extra == 'forbid'` does not result in
 |          an error if extra values are passed, but they will be ignored.
 |
 |      Args:
 |          _fields_set: A set of field names that were originally explicitly set during instantiation. If provided,
 |              this is directly used for the [`model_fields_set`][pydantic.BaseModel.model_fields_set] attribute.
 |              Otherwise, the field names from the `values` argument will be used.
 |          values: Trusted or pre-validated data dictionary.
 |
 |      Returns:
 |          A new instance of the `Model` class with validated data.
 |
 |  model_json_schema(
 |      by_alias: 'bool' = True,
 |      ref_template: 'str' = '#/$defs/{model}',
 |      schema_generator: 'type[GenerateJsonSchema]' = <class 'pydantic.json_schema.GenerateJsonSchema'>,
 |      mode: 'JsonSchemaMode' = 'validation',
 |      *,
 |      union_format: "Literal['any_of', 'primitive_type_array']" = 'any_of'
 |  ) -> 'dict[str, Any]'
 |      Generates a JSON schema for a model class.
 |
 |      Args:
 |          by_alias: Whether to use attribute aliases or not.
 |          ref_template: The reference template.
 |          union_format: The format to use when combining schemas from unions together. Can be one of:
 |
 |              - `'any_of'`: Use the [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining#anyOf)
 |              keyword to combine schemas (the default).
 |              - `'primitive_type_array'`: Use the [`type`](https://json-schema.org/understanding-json-schema/reference/type)
 |              keyword as an array of strings, containing each type of the combination. If any of the schemas is not a primitive
 |              type (`string`, `boolean`, `null`, `integer` or `number`) or contains constraints/metadata, falls back to
 |              `any_of`.
 |          schema_generator: To override the logic used to generate the JSON schema, as a subclass of
 |              `GenerateJsonSchema` with your desired modifications
 |          mode: The mode in which to generate the schema.
 |
 |      Returns:
 |          The JSON schema for the given model class.
 |
 |  model_parametrized_name(params: 'tuple[type[Any], ...]') -> 'str'
 |      Compute the class name for parametrizations of generic classes.
 |
 |      This method can be overridden to achieve a custom naming scheme for generic BaseModels.
 |
 |      Args:
 |          params: Tuple of types of the class. Given a generic class
 |              `Model` with 2 type variables and a concrete model `Model[str, int]`,
 |              the value `(str, int)` would be passed to `params`.
 |
 |      Returns:
 |          String representing the new class where `params` are passed to `cls` as type variables.
 |
 |      Raises:
 |          TypeError: Raised when trying to generate concrete names for non-generic models.
 |
 |  model_rebuild(
 |      *,
 |      force: 'bool' = False,
 |      raise_errors: 'bool' = True,
 |      _parent_namespace_depth: 'int' = 2,

In [16]:
from dbrepo.api.dto import QueryDefinition

print(QueryDefinition.model_fields.keys())

dict_keys(['columns', 'datasources', 'joins', 'filters', 'orders'])

In [17]:
for k, v in QueryDefinition.model_fields.items():
    print(k, "->", v)

columns -> annotation=List[str] required=True
datasources -> annotation=List[str] required=True
joins -> annotation=Union[List[JoinDefinition], NoneType] required=False default=None
filters -> annotation=Union[List[FilterDefinition], NoneType] required=False default=None
orders -> annotation=Union[List[OrderDefinition], NoneType] required=False default=None

In [18]:
from dbrepo.api.dto import JoinDefinition

print(JoinDefinition.model_fields.keys())

for k,v in JoinDefinition.model_fields.items():
    print(k, "->", v)

dict_keys(['type', 'datasource', 'conditionals'])
type -> annotation=ForwardRef('JoinType') required=True
datasource -> annotation=str required=True
conditionals -> annotation=ForwardRef('List[ConditionalDefinition]') required=True

In [19]:
from dbrepo.api.dto import FilterDefinition

print(FilterDefinition.model_fields.keys())

for k,v in FilterDefinition.model_fields.items():
    print(k, "->", v)

dict_keys(['type', 'column', 'operator', 'value'])
type -> annotation=FilterType required=True
column -> annotation=Union[str, NoneType] required=False default=None
operator -> annotation=Union[str, NoneType] required=False default=None
value -> annotation=Union[str, NoneType] required=False default=None

In [20]:
from dbrepo.api.dto import OrderDefinition

print(OrderDefinition.model_fields.keys())

for k,v in OrderDefinition.model_fields.items():
    print(k, "->", v)

dict_keys(['column', 'direction'])
column -> annotation=str required=True
direction -> annotation=Union[OrderType, NoneType] required=False default=None

In [21]:
from dbrepo.api.dto import ConditionalDefinition

print(ConditionalDefinition.model_fields.keys())

for k,v in ConditionalDefinition.model_fields.items():
    print(k, "->", v)

dict_keys(['column', 'foreign_column'])
column -> annotation=str required=True
foreign_column -> annotation=str required=True

In [22]:
from dbrepo.api.dto import JoinType, FilterType

print(list(JoinType))
print(list(FilterType))

[<JoinType.INNER: 'inner'>, <JoinType.LEFT: 'left'>, <JoinType.RIGHT: 'right'>, <JoinType.CROSS: 'cross'>]
[<FilterType.WHERE: 'where'>, <FilterType.OR: 'or'>, <FilterType.AND: 'and'>]

In [23]:
from dbrepo.api.dto import (
    QueryDefinition,
    JoinDefinition,
    ConditionalDefinition,
    JoinType
)

DATABASE_ID = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

query = QueryDefinition(
    datasources=[
        "coffee_consumption",
        "sleep_metrics"
    ],
    columns=[
        "coffee_consumption.participant_id",
        "coffee_consumption.coffee_intake_cups_per_day",
        "coffee_consumption.caffeine_mg_per_day",
        "sleep_metrics.sleep_hours",
        "sleep_metrics.sleep_quality"
    ],
    joins=[
        JoinDefinition(
            type=JoinType.INNER,
            datasource="sleep_metrics",
            conditionals=[
                ConditionalDefinition(
                    column="coffee_consumption.participant_id",
                    foreign_column="sleep_metrics.participant_id"
                )
            ]
        )
    ]
)

view = client.create_view(
    database_id=DATABASE_ID,
    name="coffee_sleep_view",
    query=query,
    is_public=True,
    is_schema_public=True
)

print(view)

MalformedError: Failed to map subset: column(s) not found in database 6 != 5

In [24]:
DATABASE_ID = "a6229b2e-5a3d-4a46-93aa-e9474f492ec1"

for table in client.get_tables(DATABASE_ID):
    if table.name in ["coffee_consumption", "sleep_metrics"]:
        print("\nTABLE:", table.name)

        df = client.get_table_data(
            database_id=DATABASE_ID,
            table_id=table.id,
            page=0,
            size=1
        )

        print(df.columns.tolist())

TABLE: coffee_consumption
['caffeine_mg_per_day', 'coffee_intake_cups_per_day', 'participant_id']

TABLE: sleep_metrics
['participant_id', 'sleep_hours', 'sleep_quality']

In [25]:
from dbrepo.api.dto import QueryDefinition

query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "participant_id",
        "coffee_intake_cups_per_day",
        "caffeine_mg_per_day"
    ]
)

view = client.create_view(
    database_id=DATABASE_ID,
    name="coffee_only_view",
    query=query,
    is_public=True,
    is_schema_public=True
)

print(view)

MalformedError: Failed to map subset: column(s) are not in table.column notion: ['participant_id', 'coffee_intake_cups_per_day', 'caffeine_mg_per_day']

In [26]:
db = client.get_database(DATABASE_ID)

for table in db.tables:
    print("\nTABLE:", table.internal_name)

    if hasattr(table, "columns"):
        for col in table.columns:
            print("   ", col.internal_name)

TABLE: health_metrics
    participant_id
    bmi
    heart_rate_bpm
    health_issues

TABLE: lifestyle_metrics
    participant_id
    stress_level
    physical_activity_hours
    smoking
    alcohol_consumption

TABLE: coffee_consumption
    participant_id
    coffee_intake_cups_per_day
    caffeine_mg_per_day

TABLE: sleep_metrics
    participant_id
    sleep_hours
    sleep_quality

TABLE: participants
    participant_id
    age
    gender_id
    country_id
    occupation_id

TABLE: occupations
    occupation_id
    occupation_name

TABLE: genders
    gender_id
    gender_name

TABLE: countries
    country_id
    country_name

In [27]:
help(client.create_subset)

Help on method create_subset in module dbrepo.RestClient:

create_subset(
    database_id: str,
    query: dbrepo.api.dto.QueryDefinition,
    page: int = 0,
    size: int = 1000000,
    timestamp: datetime.datetime = None
) -> pandas.DataFrame method of dbrepo.RestClient.RestClient instance
    Executes a SQL query in a database where the current user has at least read access with the given database id.
    The result set can be paginated with setting page and size (both). Historic data can be queried by setting
    timestamp.

    The `query` parameter can be difficult to set for complex subsets involving joins. We give a full example:

    ```python
    from dbrepo.api.dto import QueryDefinition, JoinDefinition, JoinType, ConditionalDefinition, FilterDefinition,             FilterType, OrderDefinition, OrderType

    query = QueryDefinition(datasources=["some_table"],
                            columns=["some_table.id", "some_table.username", "other_table.city"],
                            joins=[JoinDefinition(type=JoinType.INNER,
                                                  datasource="other_table",
                                                  conditionals=[ConditionalDefinition(
                                                      column="some_table.username",
                                                      foreign_column="other_table.username")])],
                            filters=[FilterDefinition(type=FilterType.WHERE,
                                                      column="some_table.age",
                                                      operator=">",
                                                      value="18"),
                                     FilterDefinition(type=FilterType.AND),
                                     FilterDefinition(type=FilterType.WHERE,
                                                      column="some_table.zip",
                                                      operator="=",
                                                      value="1040")],
                            orders=[OrderDefinition(column="some_table.username", direction=OrderType.ASC)])
    ```

    :param database_id: The database id.
    :param query: The query definition.
    :param page: The result pagination number. Optional. Default: `0`.
    :param size: The result pagination size. Optional. Default: `1000000`.
    :param timestamp: The timestamp at which the data validity is set. Optional. Default: <current timestamp>.

    :returns: The result set, if successful.

    :raises MalformedError: If the payload is rejected by the service.
    :raises ForbiddenError: If something went wrong with the authorization.
    :raises NotExistsError: If the database, table or user does not exist.
    :raises QueryStoreError: The query store rejected the query.
    :raises FormatNotAvailable: The subset query contains non-supported keywords.
    :raises ServiceError: If something went wrong with obtaining the information in the data service.
    :raises ResponseCodeError: If something went wrong with the retrieval.

In [28]:
from dbrepo.api.dto import QueryDefinition, FilterDefinition, FilterType

query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.participant_id",
        "coffee_consumption.coffee_intake_cups_per_day",
        "coffee_consumption.caffeine_mg_per_day"
    ],
    filters=[
        FilterDefinition(
            type=FilterType.WHERE,
            column="coffee_consumption.coffee_intake_cups_per_day",
            operator=">=",
            value="4"
        )
    ]
)

subset = client.create_subset(
    database_id=DATABASE_ID,
    query=query
)

subset.head()

2026-05-30 21:15:04,507 root         INFO   Created subset with id: db9d305d-5c5b-11f1-a854-82203d8a5a43

   caffeine_mg_per_day  coffee_intake_cups_per_day  participant_id
0                502.5                         5.3              75
1                465.6                         4.9              98
2                511.4                         5.4              67
3                395.9                         4.2              94
4                404.0                         4.3              96

In [29]:
subset.to_csv("high_coffee_consumers_subset.csv", index=False)

In [30]:
print(subset.shape)
subset.head(10)

(16, 3)

   caffeine_mg_per_day  coffee_intake_cups_per_day  participant_id
0                502.5                         5.3              75
1                465.6                         4.9              98
2                511.4                         5.4              67
3                395.9                         4.2              94
4                404.0                         4.3              96
5                441.9                         4.7              13
6                503.7                         5.3               3
7                409.5                         4.3              19
8                385.2                         4.1              12
9                413.8                         4.4              34

In [31]:
query2 = QueryDefinition(
    datasources=["sleep_metrics"],
    columns=[
        "sleep_metrics.participant_id",
        "sleep_metrics.sleep_hours",
        "sleep_metrics.sleep_quality"
    ],
    filters=[
        FilterDefinition(
            type=FilterType.WHERE,
            column="sleep_metrics.sleep_hours",
            operator="<",
            value="6"
        )
    ]
)

poor_sleep_subset = client.create_subset(
    database_id=DATABASE_ID,
    query=query2
)

poor_sleep_subset.head()

2026-05-30 21:15:36,354 root         INFO   Created subset with id: eeec4b9a-5c5b-11f1-a854-82203d8a5a43

   participant_id  sleep_hours sleep_quality
0              25          5.0          Poor
1              46          4.8          Poor
2              90          4.6          Poor
3              24          5.7          Fair
4              50          5.8          Fair

In [32]:
database = client.get_database(DATABASE_ID)

print("VIEWS:")
for v in database.views:
    print(v.name)
    print(v.internal_name)
    print("-----")

VIEWS:

In [33]:
from dbrepo.api.dto import QueryDefinition

query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.participant_id",
        "coffee_consumption.coffee_intake_cups_per_day"
    ]
)

result = client.create_subset(
    database_id=DATABASE_ID,
    query=query
)

print(result.head())

2026-05-30 21:16:48,439 root         INFO   Created subset with id: 19544ab1-5c5c-11f1-a854-82203d8a5a43
   coffee_intake_cups_per_day  participant_id
0                         5.3              75
1                         0.1              65
2                         1.1              58
3                         1.6              56
4                         0.8              51

In [34]:
database = client.get_database(DATABASE_ID)

for v in database.views:
    print(v)

In [35]:
subset = client.get_subset(
    "19544ab1-5c5c-11f1-a854-82203d8a5a43"
)

print(subset)

TypeError: RestClient.get_subset() missing 1 required positional argument: 'subset_id'

In [36]:
all_subsets = client.get_subset_data(
    "19544ab1-5c5c-11f1-a854-82203d8a5a43"
)

all_subsets.head()

TypeError: RestClient.get_subset_data() missing 1 required positional argument: 'subset_id'

In [37]:
help(client.get_subset)

Help on method get_subset in module dbrepo.RestClient:

get_subset(database_id: str, subset_id: str) -> dbrepo.api.dto.Query method of dbrepo.RestClient.RestClient instance
    Get query from a database with the given database id and query id.

    :param database_id: The database id.
    :param subset_id: The subset id.

    :returns: The query, if successful.

    :raises ForbiddenError: If something went wrong with the authorization.
    :raises NotExistsError: If the database, query or user does not exist.
    :raises FormatNotAvailable: If the service could not represent the output.
    :raises ServiceError: If something went wrong with obtaining the information in the data service.
    :raises ResponseCodeError: If something went wrong with the retrieval.

In [38]:
help(client.get_subset_data)

Help on method get_subset_data in module dbrepo.RestClient:

get_subset_data(
    database_id: str,
    subset_id: str,
    page: int = 0,
    size: int = 1000000
) -> pandas.DataFrame method of dbrepo.RestClient.RestClient instance
    Re-executes a query in a database with the given database id and query id.

    :param database_id: The database id.
    :param subset_id: The subset id.
    :param page: The result pagination number. Optional. Default: `0`.
    :param size: The result pagination size. Optional. Default: `1000000`.

    :returns: The subset data, if successful.

    :raises MalformedError: If the payload is rejected by the service.
    :raises ForbiddenError: If something went wrong with the authorization.
    :raises NotExistsError: If the database, query or user does not exist.
    :raises ServiceError: If something went wrong with obtaining the information in the data service.
    :raises ResponseCodeError: If something went wrong with the retrieval.

In [39]:
SUBSET_ID = "19544ab1-5c5c-11f1-a854-82203d8a5a43"

subset_info = client.get_subset(
    database_id=DATABASE_ID,
    subset_id=SUBSET_ID
)

print(subset_info)

id='19544ab1-5c5c-11f1-a854-82203d8a5a43' owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) execution=datetime.datetime(2026, 5, 30, 19, 16, 45) query='select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption`' type=<QueryType.QUERY: 'query'> database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' query_hash='91b0faf24dfcde8dc80168548b44be948bbcc7f40d7c78de25d6fd49d5ce4edd' is_persisted=False result_hash='b973137f7b4dcd62e4c1f00fa9ad2df02e4babee84bd011466cafcc41c0ddaf7' query_normalized="select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption` FOR SYSTEM_TIME AS OF TIMESTAMP '2026-05-30 19:16:45.609054'" result_number=100 identifiers=[]

In [40]:
query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.participant_id",
        "coffee_consumption.coffee_intake_cups_per_day"
    ]
)

subset1 = client.create_subset(
    database_id=DATABASE_ID,
    query=query
)

2026-05-30 21:18:40,743 root         INFO   Created subset with id: 5c5febb5-5c5c-11f1-91cb-12e63946ac86

In [41]:
subset1 = client.get_subset(
    database_id=DATABASE_ID,
    subset_id="19544ab1-5c5c-11f1-a854-82203d8a5a43"
)

subset2 = client.get_subset(
    database_id=DATABASE_ID,
    subset_id="5c5febb5-5c5c-11f1-91cb-12e63946ac86"
)

print(subset1)
print()
print(subset2)

id='19544ab1-5c5c-11f1-a854-82203d8a5a43' owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) execution=datetime.datetime(2026, 5, 30, 19, 16, 45) query='select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption`' type=<QueryType.QUERY: 'query'> database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' query_hash='91b0faf24dfcde8dc80168548b44be948bbcc7f40d7c78de25d6fd49d5ce4edd' is_persisted=False result_hash='b973137f7b4dcd62e4c1f00fa9ad2df02e4babee84bd011466cafcc41c0ddaf7' query_normalized="select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption` FOR SYSTEM_TIME AS OF TIMESTAMP '2026-05-30 19:16:45.609054'" result_number=100 identifiers=[]

id='5c5febb5-5c5c-11f1-91cb-12e63946ac86' owner=UserBrief(username='gokayyil', id=None, name=None, orcid=None, qualified_name=None, given_name=None, family_name=None) execution=datetime.datetime(2026, 5, 30, 19, 18, 38) query='select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption`' type=<QueryType.QUERY: 'query'> database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' query_hash='12a228acd491a3f0123bd7d4a307a7d9fa659a8f54d4b6fc13f62f711d3784df' is_persisted=False result_hash='b973137f7b4dcd62e4c1f00fa9ad2df02e4babee84bd011466cafcc41c0ddaf7' query_normalized="select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption` FOR SYSTEM_TIME AS OF TIMESTAMP '2026-05-30 19:18:38.117370'" result_number=100 identifiers=[]

In [42]:
db = client.get_database(DATABASE_ID)

print("Views:", len(db.views))

for v in db.views:
    print(v)

Views: 0

In [43]:
print(db.model_dump().keys())

dict_keys(['id', 'name', 'exchange_name', 'internal_name', 'is_public', 'is_schema_public', 'is_dashboard_enabled', 'container', 'owner', 'contact', 'identifiers', 'subsets', 'tables', 'views', 'accesses', 'preview_image', 'description', 'dashboard_uid'])

In [44]:
print(db.model_dump())

{'id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'coffee_productivity_prediction', 'exchange_name': 'dbrepo', 'internal_name': 'coffee_productivity_prediction_wbmm', 'is_public': True, 'is_schema_public': True, 'is_dashboard_enabled': True, 'container': {'id': '6cfb3b8e-1792-4e46-871a-f3d103527203', 'name': 'mariadb-galera:11.3.2', 'image': {'id': 'd79cb089-363c-488b-9717-649e44d8fcc5', 'name': 'mariadb', 'version': '11.1.3', 'default': False}, 'internal_name': 'mariadb_11_3_2', 'running': None, 'hash': None}, 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'contact': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'identifiers': [], 'subsets': [], 'tables': [{'id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'health_metrics', 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'columns': [{'id': 'ff8a6b23-c905-4330-96ea-1d8ca2619ee0', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'ord': 0, 'internal_name': 'participant_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 50.5, 'median': 50.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 28.8661}, {'id': '57182a37-055a-4a39-84e5-6b7b6729943c', 'name': 'bmi', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'ord': 1, 'internal_name': 'bmi', 'is_null_allowed': False, 'type': <ColumnType.DECIMAL: 'decimal'>, 'alias': None, 'description': None, 'size': 40, 'd': 20, 'mean': 23.239, 'median': 23.239, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 4.2094}, {'id': 'd70581d8-2436-4410-9ce7-eb6dea905b18', 'name': 'heart_rate_bpm', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'ord': 2, 'internal_name': 'heart_rate_bpm', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 70.3, 'median': 70.3, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 9.376}, {'id': 'ad57b8a8-146c-44be-92f4-8a921519ac60', 'name': 'health_issues', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'ord': 3, 'internal_name': 'health_issues', 'is_null_allowed': False, 'type': <ColumnType.TEXT: 'text'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 4.16, 'median': 4.16, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 0.7838}], 'constraints': {'uniques': [], 'foreign_keys': [], 'checks': [], 'primary_key': [{'id': 'afb6c36f-02ea-4b5d-9a02-a87b498068dd', 'table': {'id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'health_metrics', 'description': 'Table containing BMI, heart rate, and reported health issue category.', 'internal_name': 'health_metrics', 'is_versioned': True, 'is_public': True, 'is_schema_public': True, 'owned_by': 'gokayyil'}, 'column': {'id': 'ff8a6b23-c905-4330-96ea-1d8ca2619ee0', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'internal_name': 'participant_id', 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None}}]}, 'internal_name': 'health_metrics', 'is_versioned': True, 'queue_name': 'dbrepo', 'routing_key': 'dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.9abc69b3-932e-4a20-93a6-9e3cb4ac9676', 'is_public': True, 'is_schema_public': True, 'identifiers': [], 'description': 'Table containing BMI, heart rate, and reported health issue category.', 'queue_type': 'quorum', 'num_rows': 100, 'data_length': 16384, 'max_data_length': 0, 'avg_row_length': 163}, {'id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'lifestyle_metrics', 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'columns': [{'id': 'bcd68c6c-63b8-4774-97cd-dcae2f006ff6', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'ord': 0, 'internal_name': 'participant_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 50.5, 'median': 50.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 28.8661}, {'id': '52e33311-e40d-49e2-8cef-9fd8f8afa76d', 'name': 'stress_level', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'ord': 1, 'internal_name': 'stress_level', 'is_null_allowed': False, 'type': <ColumnType.TEXT: 'text'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 3.54, 'median': 3.54, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 1.0993}, {'id': '49a0379f-dc64-48be-b0a3-21056dcab329', 'name': 'physical_activity_hours', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'ord': 2, 'internal_name': 'physical_activity_hours', 'is_null_allowed': False, 'type': <ColumnType.DECIMAL: 'decimal'>, 'alias': None, 'description': None, 'size': 40, 'd': 20, 'mean': 7.868, 'median': 7.868, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 4.1667}, {'id': 'bdd0b95f-e4f1-41ac-ab26-79d0b7c9ee7b', 'name': 'smoking', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'ord': 3, 'internal_name': 'smoking', 'is_null_allowed': False, 'type': <ColumnType.BOOL: 'bool'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 0.23, 'median': 0.23, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 0.4208}, {'id': '2f8086e1-d73b-4358-9ef8-e87d1b4bebae', 'name': 'alcohol_consumption', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'ord': 4, 'internal_name': 'alcohol_consumption', 'is_null_allowed': False, 'type': <ColumnType.BOOL: 'bool'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 0.27, 'median': 0.27, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 0.444}], 'constraints': {'uniques': [], 'foreign_keys': [], 'checks': [], 'primary_key': [{'id': 'c9ae6b9a-c6f1-4765-9c3b-05f9833d1e00', 'table': {'id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'lifestyle_metrics', 'description': 'Table containing stress level, physical activity duration, smoking status, and alcohol consumption status.', 'internal_name': 'lifestyle_metrics', 'is_versioned': True, 'is_public': True, 'is_schema_public': True, 'owned_by': 'gokayyil'}, 'column': {'id': 'bcd68c6c-63b8-4774-97cd-dcae2f006ff6', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': 'dddb6b09-ba3f-4003-bf93-73786410e886', 'internal_name': 'participant_id', 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None}}]}, 'internal_name': 'lifestyle_metrics', 'is_versioned': True, 'queue_name': 'dbrepo', 'routing_key': 'dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.dddb6b09-ba3f-4003-bf93-73786410e886', 'is_public': True, 'is_schema_public': True, 'identifiers': [], 'description': 'Table containing stress level, physical activity duration, smoking status, and alcohol consumption status.', 'queue_type': 'quorum', 'num_rows': 100, 'data_length': 16384, 'max_data_length': 0, 'avg_row_length': 163}, {'id': '6e828acb-4698-4f34-9a62-1a753b768554', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'coffee_consumption', 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'columns': [{'id': 'ea78c4ce-44da-4468-b4d7-3880baf9b1e1', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '6e828acb-4698-4f34-9a62-1a753b768554', 'ord': 0, 'internal_name': 'participant_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 50.5, 'median': 50.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 28.8661}, {'id': 'd3cf2175-5393-43d6-8707-31a39be698b4', 'name': 'coffee_intake_cups_per_day', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '6e828acb-4698-4f34-9a62-1a753b768554', 'ord': 1, 'internal_name': 'coffee_intake_cups_per_day', 'is_null_allowed': False, 'type': <ColumnType.DECIMAL: 'decimal'>, 'alias': None, 'description': None, 'size': 40, 'd': 20, 'mean': 2.363, 'median': 2.363, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 1.3713}, {'id': 'f5f80e8f-af51-4961-bf4d-7ff65264aa6b', 'name': 'caffeine_mg_per_day', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '6e828acb-4698-4f34-9a62-1a753b768554', 'ord': 2, 'internal_name': 'caffeine_mg_per_day', 'is_null_allowed': False, 'type': <ColumnType.DECIMAL: 'decimal'>, 'alias': None, 'description': None, 'size': 40, 'd': 20, 'mean': 224.407, 'median': 224.407, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 130.0596}], 'constraints': {'uniques': [], 'foreign_keys': [], 'checks': [], 'primary_key': [{'id': 'a5cc08a3-7f36-4a92-8ec5-91fd99a92191', 'table': {'id': '6e828acb-4698-4f34-9a62-1a753b768554', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'coffee_consumption', 'description': 'Table containing daily coffee intake in cups and daily caffeine intake in milligrams.', 'internal_name': 'coffee_consumption', 'is_versioned': True, 'is_public': True, 'is_schema_public': True, 'owned_by': 'gokayyil'}, 'column': {'id': 'ea78c4ce-44da-4468-b4d7-3880baf9b1e1', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '6e828acb-4698-4f34-9a62-1a753b768554', 'internal_name': 'participant_id', 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None}}]}, 'internal_name': 'coffee_consumption', 'is_versioned': True, 'queue_name': 'dbrepo', 'routing_key': 'dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.6e828acb-4698-4f34-9a62-1a753b768554', 'is_public': True, 'is_schema_public': True, 'identifiers': [], 'description': 'Table containing daily coffee intake in cups and daily caffeine intake in milligrams.', 'queue_type': 'quorum', 'num_rows': 100, 'data_length': 16384, 'max_data_length': 0, 'avg_row_length': 163}, {'id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'sleep_metrics', 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'columns': [{'id': '26c1d10d-9751-4df2-8816-039d35e65d00', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'ord': 0, 'internal_name': 'participant_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 50.5, 'median': 50.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 28.8661}, {'id': '90dfad3a-4f42-4195-b611-33c45afcb1d1', 'name': 'sleep_hours', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'ord': 1, 'internal_name': 'sleep_hours', 'is_null_allowed': False, 'type': <ColumnType.DECIMAL: 'decimal'>, 'alias': None, 'description': None, 'size': 40, 'd': 20, 'mean': 6.742, 'median': 6.742, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 1.0433}, {'id': '04efe6b6-5237-403e-9600-4531306a050d', 'name': 'sleep_quality', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'ord': 2, 'internal_name': 'sleep_quality', 'is_null_allowed': False, 'type': <ColumnType.TEXT: 'text'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 4.5, 'median': 4.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 1.5}], 'constraints': {'uniques': [], 'foreign_keys': [], 'checks': [], 'primary_key': [{'id': '3d3d34b2-0999-48bb-974e-87c1c448607c', 'table': {'id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'sleep_metrics', 'description': 'Table containing sleep duration and sleep quality information.', 'internal_name': 'sleep_metrics', 'is_versioned': True, 'is_public': True, 'is_schema_public': True, 'owned_by': 'gokayyil'}, 'column': {'id': '26c1d10d-9751-4df2-8816-039d35e65d00', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'internal_name': 'participant_id', 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None}}]}, 'internal_name': 'sleep_metrics', 'is_versioned': True, 'queue_name': 'dbrepo', 'routing_key': 'dbrepo.a6229b2e-5a3d-4a46-93aa-e9474f492ec1.83a691e2-a7ad-4b5a-b468-03c3d63d727b', 'is_public': True, 'is_schema_public': True, 'identifiers': [], 'description': 'Table containing sleep duration and sleep quality information.', 'queue_type': 'quorum', 'num_rows': 100, 'data_length': 16384, 'max_data_length': 0, 'avg_row_length': 163}, {'id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'name': 'participants', 'owner': {'username': 'gokayyil', 'id': None, 'name': None, 'orcid': None, 'qualified_name': None, 'given_name': None, 'family_name': None}, 'columns': [{'id': 'fc7636e8-1850-432b-ad5d-996a338b7ad1', 'name': 'participant_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'ord': 0, 'internal_name': 'participant_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 50.5, 'median': 50.5, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 28.8661}, {'id': '7c66c820-ea1c-46f6-8582-a5ce3415788c', 'name': 'age', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'ord': 1, 'internal_name': 'age', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 33.75, 'median': 33.75, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 9.9059}, {'id': '307909e1-d29b-4ba9-981a-ebfd50b96438', 'name': 'gender_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'ord': 2, 'internal_name': 'gender_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 1.49, 'median': 1.49, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 0.4999}, {'id': '39fd0bed-29b1-4e4f-af6b-03f2b28495a9', 'name': 'country_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'ord': 3, 'internal_name': 'country_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 9.71, 'median': 9.71, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 5.5268}, {'id': '400924f5-09d5-412c-a789-afa3b5664943', 'name': 'occupation_id', 'database_id': 'a6229b2e-5a3d-4a46-93aa-e9474f492ec1', 'table_id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'ord': 4, 'internal_name': 'occupation_id', 'is_null_allowed': False, 'type': <ColumnType.BIGINT: 'bigint'>, 'alias': None, 'description': None, 'size': None, 'd': None, 'mean': 3.32, 'median': 3.32, 'concept': None, 'unit': None, 'concept_uri': None, 'unit_uri': None, 'enums': [], 'sets': [], 'index_length': None, 'length': None, 'data_length': None, 'max_data_length': None, 'num_rows': None, 'val_min': None, 'val_max': None, 'std_dev': 1.2718}], 'constraints': {'uniques': [], 'foreign_keys': [], 'checks': [], 'primary_key': [{'id': '416d6f45-c608-4d0d-9079-eb75d85c8276', 'table': {'id': '913c5c1d-3e46-4393-9e5e-744ab04e0ad2', 'database_id': 'a6229b2e-5a

In [45]:
[m for m in dir(client) if "view" in m.lower()]

['create_view',
 'delete_view',
 'get_view',
 'get_view_data',
 'get_view_data_count',
 'get_views',
 'update_view']

In [46]:
help(client.create_view)

Help on method create_view in module dbrepo.RestClient:

create_view(
    database_id: str,
    name: str,
    query: dbrepo.api.dto.QueryDefinition,
    is_public: bool,
    is_schema_public: bool
) -> dbrepo.api.dto.ViewBrief method of dbrepo.RestClient.RestClient instance
    Create a view in a database with the given database id.

    :param database_id: The database id.
    :param name: The name of the created view.
    :param query: The query definition of the view.
    :param is_public: The visibility of the data. If set to `True` the data will be publicly visible. Optional. Default: `True`.
    :param is_schema_public: The visibility of the schema metadata. If set to `True` the schema metadata will be publicly visible. Optional. Default: `True`.

    :returns: The created view, if successful.

    :raises MalformedError: If the payload is rejected by the service.
    :raises ForbiddenError: If something went wrong with the authorization.
    :raises NotExistsError: If the database does not exist.
    :raises ExternalSystemError: If the mapped view creation query is erroneous.
    :raises ServiceConnectionError: If something went wrong with the connection to the search service.
    :raises ServiceError: If something went wrong with obtaining the information in the search service.
    :raises ResponseCodeError: If something went wrong with the retrieval.

In [48]:
db = client.get_database(DATABASE_ID)

for t in db.tables:
    print("\nTABLE:", t.internal_name)

    for c in t.columns:
        print("   ", c.internal_name)

TABLE: health_metrics
    participant_id
    bmi
    heart_rate_bpm
    health_issues

TABLE: lifestyle_metrics
    participant_id
    stress_level
    physical_activity_hours
    smoking
    alcohol_consumption

TABLE: coffee_consumption
    participant_id
    coffee_intake_cups_per_day
    caffeine_mg_per_day

TABLE: sleep_metrics
    participant_id
    sleep_hours
    sleep_quality

TABLE: participants
    participant_id
    age
    gender_id
    country_id
    occupation_id

TABLE: occupations
    occupation_id
    occupation_name

TABLE: genders
    gender_id
    gender_name

TABLE: countries
    country_id
    country_name

In [49]:
from dbrepo.api.dto import QueryDefinition

query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.participant_id",
        "coffee_consumption.coffee_intake_cups_per_day"
    ]
)

view = client.create_view(
    database_id=DATABASE_ID,
    name="test_view",
    query=query,
    is_public=True,
    is_schema_public=True
)

print(view)

id='dab5269f-5669-4797-9853-744a824ac610' database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1' name='test_view' internal_name='test_view' is_public=True is_schema_public=True initial_view=False query='select `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` from `coffee_consumption`' query_hash='93c0036a9a9b5028d47278ca7435a0187285c79f780f1c8989ce1d593d1ccdb4' owned_by='gokayyil'

In [52]:
query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.coffee_intake_cups_per_day",
        "coffee_consumption.caffeine_mg_per_day",
        "sleep_metrics.sleep_hours",
        "sleep_metrics.sleep_quality"
    ],
    joins=[
        JoinDefinition(
            type=JoinType.INNER,
            datasource="sleep_metrics",
            conditionals=[
                ConditionalDefinition(
                    column="coffee_consumption.participant_id",
                    foreign_column="sleep_metrics.participant_id"
                )
            ]
        )
    ]
)

client.create_view(
    database_id=DATABASE_ID,
    name="vw_coffee_sleep",
    query=query,
    is_public=True,
    is_schema_public=True
)

ViewBrief(id='27efd1f1-f6bb-45af-a30e-24fbb2dc12ac', database_id='a6229b2e-5a3d-4a46-93aa-e9474f492ec1', name='vw_coffee_sleep', internal_name='vw_coffee_sleep', is_public=True, is_schema_public=True, initial_view=False, query='select `coffee_productivity_prediction_wbmm`.`sleep_metrics`.`sleep_quality`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`coffee_intake_cups_per_day`, `coffee_productivity_prediction_wbmm`.`sleep_metrics`.`sleep_hours`, `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`caffeine_mg_per_day` from `coffee_consumption` join `sleep_metrics` on `coffee_productivity_prediction_wbmm`.`coffee_consumption`.`participant_id` = `coffee_productivity_prediction_wbmm`.`sleep_metrics`.`participant_id`', query_hash='7b00a1f16b2dec45f083d447d4e263f269be600a7e7e3ea148071be04e0511c2', owned_by='gokayyil')

In [53]:
query = QueryDefinition(
    datasources=["coffee_consumption"],
    columns=[
        "coffee_consumption.coffee_intake_cups_per_day",
        "coffee_consumption.caffeine_mg_per_day",
        "participants.age"
    ],
    joins=[
        JoinDefinition(
            type=JoinType.INNER,
            datasource="participants",
            conditionals=[
                ConditionalDefinition(
                    column="coffee_consumption.participant_id",
                    foreign_column="participants.participant_id"
                )
            ]
        )
    ]
)

client.create_view(
    database_id=DATABASE_ID,
    name="vw_coffee_demographics",
    query=query,
    is_public=True,
    is_schema_public=True
)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [54]:
views = client.get_views(DATABASE_ID)

for v in views:
    print(v.name)

vw_coffee_sleep
test_join_view
test_view